### ISSUE TITLE
`contest_path` not processed

### ISSUE THREAD

**Issue by jl0x61** [xdu-icpc/cftool#1]
`cargo run -- -d` failed but `cargo run -- -d -o gym/102309` succeeded.
It seems that [from_file](https://github.com/xdu-icpc/cftool/blob/9b576c571e788db4da8799192d331d7109dc9ac3/src/codeforces.rs#L80) method doesn't process the `contest_path` field.
My `cftool.json` is below.
```json
{
    "identy": "jl0x62",
    "server_url": "https://codeforces.com",
    "contest_path": "gym/102309",
    "prefer_cxx": "c++11"
}
```
The error message:
```
ERROR - no contest URL provided
```

**Comment by xry111** [comment]
Confirmed.  It's a regression introduced by 85e394fc.
